% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Feb-2025 23:51:19
%  MATLAB version: 24.1.0.2653294 (R2024a) Update 5
% -------------------------------------------------------------------
                                                 
filename="ARTTU";

hrdPtFr=read_excel(filename,'HardpointsFr','UseRowNames',true)./1000;
hrdPtFr.X=-hrdPtFr.X;

hrdPtRr=read_excel(filename,'HardpointsRr','UseRowNames',true)./1000;
hrdPtRr.X=-hrdPtRr.X;
%% Body
Vehicle = struct;
Vehicle.Chassis = struct;
Vehicle.Chassis.Body = struct;
Vehicle.Chassis.Body.class = struct;
Vehicle.Chassis.Body.class.Value = 'Body_Axle2';
Vehicle.Chassis.Body.sAxle1 = struct;
Vehicle.Chassis.Body.sAxle1.Units = 'm';
Vehicle.Chassis.Body.sAxle1.Comments = '';
Vehicle.Chassis.Body.sAxle1.Value = ...
  [0 0 0];
Vehicle.Chassis.Body.sAxle2 = struct;
Vehicle.Chassis.Body.sAxle2.Units = 'm';
Vehicle.Chassis.Body.sAxle2.Comments = '';
Vehicle.Chassis.Body.sAxle2.Value = ...
  [-1.575 0 0];
Vehicle.Chassis.Body.sCG = struct;
Vehicle.Chassis.Body.sCG.Units = 'm';
Vehicle.Chassis.Body.sCG.Comments = '';
Vehicle.Chassis.Body.sCG.Value = [-0.8741 0 0.35];
Vehicle.Chassis.Body.sPower = struct;
Vehicle.Chassis.Body.sPower.Units = 'm';
Vehicle.Chassis.Body.sPower.Comments = '';
Vehicle.Chassis.Body.sPower.Value = ...
  [-1 0 0];
Vehicle.Chassis.Body.sHitchF = struct;
Vehicle.Chassis.Body.sHitchF.Units = 'm';
Vehicle.Chassis.Body.sHitchF.Comments = '';
Vehicle.Chassis.Body.sHitchF.Value = ...
  [0.25 0 0.403];
Vehicle.Chassis.Body.sHitchR = struct;
Vehicle.Chassis.Body.sHitchR.Units = 'm';
Vehicle.Chassis.Body.sHitchR.Comments = '';
Vehicle.Chassis.Body.sHitchR.Value = ...
  [-1.75 0 0.403];
Vehicle.Chassis.Body.Width = struct;
Vehicle.Chassis.Body.Width.Units = 'm';
Vehicle.Chassis.Body.Width.Comments = 'Wheel Center Y*2+0.2';
Vehicle.Chassis.Body.Width.Value =  ((hrdPtFr{"wheelCenter","Y"}*2 ) + (hrdPtRr{"wheelCenter","Y"}*2))/2 ;
Vehicle.Chassis.Body.TrackFront = struct;
Vehicle.Chassis.Body.TrackFront.Units = 'm';
Vehicle.Chassis.Body.TrackFront.Comments = 'Wheel Center Y*2+0.2';
Vehicle.Chassis.Body.TrackFront.Value = hrdPtFr{"wheelCenter","Y"}*2 ;
Vehicle.Chassis.Body.TrackRear = struct;
Vehicle.Chassis.Body.TrackRear.Units = 'm';
Vehicle.Chassis.Body.TrackRear.Comments = 'Wheel Center Y*2+0.2';
Vehicle.Chassis.Body.TrackRear.Value = hrdPtRr{"wheelCenter",'Y'}*2 ;
Vehicle.Chassis.Body.m = struct;
Vehicle.Chassis.Body.m.Units = 'kg';
Vehicle.Chassis.Body.m.Comments = '';
Vehicle.Chassis.Body.m.Value =195.7;
Vehicle.Chassis.Body.J = struct;
Vehicle.Chassis.Body.J.Units = 'kg*m^2';
Vehicle.Chassis.Body.J.Comments = 'Moments of Inertia [Ixx Iyy Izz]';
Vehicle.Chassis.Body.J.Value = [43 192 206];
Vehicle.Chassis.Body.Type = 'Body';
Vehicle.Chassis.Body.Instance = 'FSAE_Achilles';
Vehicle.Chassis.Body.BodyGeometry = struct;
Vehicle.Chassis.Body.BodyGeometry.class = struct;
Vehicle.Chassis.Body.BodyGeometry.class.Value = 'CAD_FSAE_Achilles';
Vehicle.Chassis.Body.BodyGeometry.sOffset = struct;
Vehicle.Chassis.Body.BodyGeometry.sOffset.Units = 'm';
Vehicle.Chassis.Body.BodyGeometry.sOffset.Comments = '';
Vehicle.Chassis.Body.BodyGeometry.sOffset.Value = ...
    [-0.5375 0 0];
Vehicle.Chassis.Body.BodyGeometry.aOffset = struct;
Vehicle.Chassis.Body.BodyGeometry.aOffset.Units = 'Yaw-Pitch-Roll';
Vehicle.Chassis.Body.BodyGeometry.aOffset.Comments = '';
Vehicle.Chassis.Body.BodyGeometry.aOffset.Value = ...
    [0 0 0];
Vehicle.Chassis.Body.BodyGeometry.Color = struct;
Vehicle.Chassis.Body.BodyGeometry.Color.Units = '[RGB]';
Vehicle.Chassis.Body.BodyGeometry.Color.Comments = '';
Vehicle.Chassis.Body.BodyGeometry.Color.Value = ...
    [0.1 0.5 0.9];
Vehicle.Chassis.Body.BodyGeometry.Opacity = struct;
Vehicle.Chassis.Body.BodyGeometry.Opacity.Units = '(0-1)';
Vehicle.Chassis.Body.BodyGeometry.Opacity.Comments = '';
Vehicle.Chassis.Body.BodyGeometry.Opacity.Value = 1;
Vehicle.Chassis.Body.BodyGeometry.AeroColor = struct;
Vehicle.Chassis.Body.BodyGeometry.AeroColor.Units = '[RGB]';
Vehicle.Chassis.Body.BodyGeometry.AeroColor.Comments = '';
Vehicle.Chassis.Body.BodyGeometry.AeroColor.Value = ...
    [0.095 0.2 0.3];
Vehicle.Chassis.Body.BodyGeometry.AeroOpacity = struct;
Vehicle.Chassis.Body.BodyGeometry.AeroOpacity.Units = '(0-1)';
Vehicle.Chassis.Body.BodyGeometry.AeroOpacity.Comments = '';
Vehicle.Chassis.Body.BodyGeometry.AeroOpacity.Value = 1;
Vehicle.Chassis.Body.BodyGeometry.Type = 'BodyGeometry';
Vehicle.Chassis.Body.BodyGeometry.Instance = 'CAD_FSAE_Achilles';
Vehicle.Chassis.Body.BodyLoad = struct;
Vehicle.Chassis.Body.BodyLoad.class = struct;
Vehicle.Chassis.Body.BodyLoad.class.Value = 'None';
Vehicle.Chassis.Body.BodyLoad.Type = 'BodyLoad';
Vehicle.Chassis.Body.BodyLoad.Instance = 'None';

clear hrdPtRr hrdPtFr;
%% Front Suspension
hrdPt=read_excel(filename,'HardpointsFr','UseRowNames',true)./1000;
% hrdPt.X=hrdPt.X;
Vehicle.Chassis.SuspA1 = struct;
Vehicle.Chassis.SuspA1.Linkage = struct;
Vehicle.Chassis.SuspA1.Linkage.class = struct;
Vehicle.Chassis.SuspA1.Linkage.class.Value = 'DoubleWishbone Pushrod';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone = struct;
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF = struct;
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardF.Value = ...
  hrdPt{'lcaF',:};
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR = struct;
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sInboardR.Value = ...
  hrdPt{'lcaR',:};
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard = struct;
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.sOutboard.Value = ...
  hrdPt{"lcaO",:};
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.m = struct;
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.m.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.LowerWishbone.m.Value = 0.2;
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone = struct;
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF = struct;
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardF.Value = ...
  hrdPt{'ucaF',:};
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR = struct;
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sInboardR.Value = ...
  hrdPt{'ucaR',:};
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard = struct;
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.sOutboard.Value = ...
  hrdPt{'ucaO',:};
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.m = struct;
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.m.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.UpperWishbone.m.Value = 0.15;
Vehicle.Chassis.SuspA1.Linkage.Upright = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.sCG = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.sCG.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Upright.sCG.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upright.sCG.Value = ...
  hrdPt{'uprightCG',:};
Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upright.sWheelCentre.Value = ...
  hrdPt{"wheelCenter",:};
Vehicle.Chassis.SuspA1.Linkage.Upright.m = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.Upright.m.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upright.m.Value = 1;
Vehicle.Chassis.SuspA1.Linkage.Upright.aToe = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.aToe.Units = 'deg';
Vehicle.Chassis.SuspA1.Linkage.Upright.aToe.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upright.aToe.Value = 0;
Vehicle.Chassis.SuspA1.Linkage.Upright.aCamber = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.aCamber.Units = 'deg';
Vehicle.Chassis.SuspA1.Linkage.Upright.aCamber.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upright.aCamber.Value = -1;
Vehicle.Chassis.SuspA1.Linkage.Upright.xAxle = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.xAxle.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Upright.xAxle.Comments = 'Axle length';
Vehicle.Chassis.SuspA1.Linkage.Upright.xAxle.Value = 0.15;
Vehicle.Chassis.SuspA1.Linkage.Upright.xWCtoBearing = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.xWCtoBearing.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Upright.xWCtoBearing.Comments = ...
  'Wheel Center to Bearing';
Vehicle.Chassis.SuspA1.Linkage.Upright.xWCtoBearing.Value = 0.05;
Vehicle.Chassis.SuspA1.Linkage.Upright.mAxle = struct;
Vehicle.Chassis.SuspA1.Linkage.Upright.mAxle.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.Upright.mAxle.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upright.mAxle.Value = 0.6;
Vehicle.Chassis.SuspA1.Linkage.TrackRod = struct;
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard = struct;
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sInboard.Value = ...
  hrdPt{'trackrodI',:};
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard = struct;
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.TrackRod.sOutboard.Value = ...
  hrdPt{'trackrodO',:};
Vehicle.Chassis.SuspA1.Linkage.TrackRod.m = struct;
Vehicle.Chassis.SuspA1.Linkage.TrackRod.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.TrackRod.m.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.TrackRod.m.Value = 0.2;
Vehicle.Chassis.SuspA1.Linkage.Shock = struct;
Vehicle.Chassis.SuspA1.Linkage.Shock.sTop = struct;
Vehicle.Chassis.SuspA1.Linkage.Shock.sTop.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Shock.sTop.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Shock.sTop.Value = ...
  hrdPt{'shockT',:};
Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom = struct;
Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Shock.sBottom.Value = ...
  hrdPt{'shockB',:};
Vehicle.Chassis.SuspA1.Linkage.Shock.mPiston = struct;
Vehicle.Chassis.SuspA1.Linkage.Shock.mPiston.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.Shock.mPiston.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Shock.mPiston.Value = 0.8;
Vehicle.Chassis.SuspA1.Linkage.Shock.mCylinder = struct;
Vehicle.Chassis.SuspA1.Linkage.Shock.mCylinder.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.Shock.mCylinder.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Shock.mCylinder.Value = 1.2;
Vehicle.Chassis.SuspA1.Linkage.Endstop = struct;
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMax = struct;
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMax.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMax.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMax.Value = 0.056/2;
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMin = struct;
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMin.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMin.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Endstop.xMin.Value = -0.056/2;
%% Front suspenison Joints
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.class = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.class.Value = ...
  'Rigid_1Rev';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law.Comments = ...
  'Linear / Table /Maxwell SLS';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1 = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1.Value = 3013.9;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1 = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1.Value = 11471;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x.Value = ...
  [-3 -1.5 1.5 3];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f.Value = ...
  [-6555 -2622 2622 6555];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.Type = ...
  'Subframe_Conn';
Vehicle.Chassis.SuspA1.Linkage.Upper_Arm_to_Subframe.Instance = ...
  'Bushing_Sedan_UA';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.class = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.class.Value = ...
  'Rigid_1Rev';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law.Comments = ...
  'Linear / Table /Maxwell SLS';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1 = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1.Value = 3013.9;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1 = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1.Value = 11471;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x.Value = ...
  [-3 -1.5 1.5 3];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f.Value = ...
  [-6555 -2622 2622 6555];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law.Units = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f = struct;
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.Type = ...
  'Subframe_Conn';
Vehicle.Chassis.SuspA1.Linkage.Lower_Arm_to_Subframe.Instance = ...
  'Bushing_Sedan_LA';
Vehicle.Chassis.SuspA1.Linkage.Pushrod = struct;
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sLowerArm = struct;
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sLowerArm.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sLowerArm.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sLowerArm.Value = ...
    hrdPt{'PushrodOut',:};
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sBellcrank = struct;
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sBellcrank.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sBellcrank.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Pushrod.sBellcrank.Value = ...
  hrdPt{'BCrod',:};
Vehicle.Chassis.SuspA1.Linkage.Pushrod.m = struct;
Vehicle.Chassis.SuspA1.Linkage.Pushrod.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.Pushrod.m.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Pushrod.m.Value = 0.2;
Vehicle.Chassis.SuspA1.Linkage.Bellcrank = struct;
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sPivot = struct;
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sPivot.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sPivot.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sPivot.Value = ...
  hrdPt{'BCpivot',:};
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sAntiRollBar = struct;
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sAntiRollBar.Units = 'm';
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sAntiRollBar.Comments = ...
  'Must be same as AntiRollBar.sSuspension';
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.sAntiRollBar.Value = ...
  hrdPt{'arbSus',:};
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.m = struct;
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.m.Comments = '';
Vehicle.Chassis.SuspA1.Linkage.Bellcrank.m.Value = 0.2;
Vehicle.Chassis.SuspA1.Linkage.Type = 'Linkage';
Vehicle.Chassis.SuspA1.Linkage.Instance = ...
  'DoubleWishbonePushrod_FSAE_Achilles_f';

%% Antiroll bar Front
ARBcoef=read_excel(filename,'Suspension','UseRowNames',true);
Vehicle.Chassis.SuspA1.class = struct;
Vehicle.Chassis.SuspA1.class.Value = 'Linkage';
Vehicle.Chassis.SuspA1.AntiRollBar = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.class = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.class.Value = 'DroplinkRod';
Vehicle.Chassis.SuspA1.AntiRollBar.sSuspension = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.sSuspension.Units = 'm';
Vehicle.Chassis.SuspA1.AntiRollBar.sSuspension.Comments = '';
Vehicle.Chassis.SuspA1.AntiRollBar.sSuspension.Value = ...
  hrdPt{'arbSus',:};
Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard.Comments = '';
Vehicle.Chassis.SuspA1.AntiRollBar.sOutboard.Value = ...
  hrdPt{'arbO',:};
Vehicle.Chassis.SuspA1.AntiRollBar.sInboard = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.sInboard.Units = 'm';
Vehicle.Chassis.SuspA1.AntiRollBar.sInboard.Comments = '';
Vehicle.Chassis.SuspA1.AntiRollBar.sInboard.Value = ...
  hrdPt{'arbI',:};
Vehicle.Chassis.SuspA1.AntiRollBar.k = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.k.Units = 'N/rad';
Vehicle.Chassis.SuspA1.AntiRollBar.k.Comments = '';
Vehicle.Chassis.SuspA1.AntiRollBar.k.Value = ARBcoef{'Stiffness','Front'};
Vehicle.Chassis.SuspA1.AntiRollBar.m = struct;
Vehicle.Chassis.SuspA1.AntiRollBar.m.Units = 'kg';
Vehicle.Chassis.SuspA1.AntiRollBar.m.Comments = '';
Vehicle.Chassis.SuspA1.AntiRollBar.m.Value = 0.7;
Vehicle.Chassis.SuspA1.AntiRollBar.Type = 'AntiRollBar';
Vehicle.Chassis.SuspA1.AntiRollBar.Instance = ...
  'Droplink_FSAE_Achilles_f';
clear ARBcoef;
%% Steering
pinionIncl=-atan((hrdPt{'upperCol','X'}-hrdPt{'steerRack','X'})/(hrdPt{'upperCol','Z'}-hrdPt{'steerRack','Z'}));
Vehicle.Chassis.SuspA1.Steer = struct;
Vehicle.Chassis.SuspA1.Steer.class = struct;
Vehicle.Chassis.SuspA1.Steer.class.Value = 'WheelDrivenRack1UJoint1';
Vehicle.Chassis.SuspA1.Steer.Rack = struct;
Vehicle.Chassis.SuspA1.Steer.Rack.sMount = struct;
Vehicle.Chassis.SuspA1.Steer.Rack.sMount.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Rack.sMount.Comments = 'HPRack';
Vehicle.Chassis.SuspA1.Steer.Rack.sMount.Value = ...
  hrdPt{'steerRack',:};
Vehicle.Chassis.SuspA1.Steer.Rack.m = struct;
Vehicle.Chassis.SuspA1.Steer.Rack.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Steer.Rack.m.Comments = 'Mass';
Vehicle.Chassis.SuspA1.Steer.Rack.m.Value = 1.8;
Vehicle.Chassis.SuspA1.Steer.Rack.fActuatorCutoff = struct;
Vehicle.Chassis.SuspA1.Steer.Rack.fActuatorCutoff.Units = 'Hz';
Vehicle.Chassis.SuspA1.Steer.Rack.fActuatorCutoff.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Rack.fActuatorCutoff.Value = 50;
Vehicle.Chassis.SuspA1.Steer.Wheel = struct;
Vehicle.Chassis.SuspA1.Steer.Wheel.sMount = struct;
Vehicle.Chassis.SuspA1.Steer.Wheel.sMount.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Wheel.sMount.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Wheel.sMount.Value = ...
  hrdPt{'steerWheel',:};
Vehicle.Chassis.SuspA1.Steer.Wheel.sUpperCol = struct;
Vehicle.Chassis.SuspA1.Steer.Wheel.sUpperCol.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Wheel.sUpperCol.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Wheel.sUpperCol.Value = ...
  hrdPt{'upperCol',:};
Vehicle.Chassis.SuspA1.Steer.Wheel.aAxis = struct;
Vehicle.Chassis.SuspA1.Steer.Wheel.aAxis.Units = 'rad';
Vehicle.Chassis.SuspA1.Steer.Wheel.aAxis.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Wheel.aAxis.Value = ...
 -atan((hrdPt{'steerWheel','Z'}-hrdPt{'upperCol','Z'})/(hrdPt{'steerWheel','X'}-hrdPt{'upperCol','X'}));
Vehicle.Chassis.SuspA1.Steer.Wheel.m = struct;
Vehicle.Chassis.SuspA1.Steer.Wheel.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Steer.Wheel.m.Comments = 'Mass';
Vehicle.Chassis.SuspA1.Steer.Wheel.m.Value = 0.7;
Vehicle.Chassis.SuspA1.Steer.Wheel.class = struct;
Vehicle.Chassis.SuspA1.Steer.Wheel.class.Value = 'FSAE';
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper = struct;
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.m = struct;
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.m.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.m.Value = 0.4;
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.xLength = struct;
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.xLength.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.xLength.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Shaft_Upper.xLength.Value = ((hrdPt{'steerWheel','X'}-hrdPt{'upperCol','X'})^2+(hrdPt{'steerWheel','X'}-hrdPt{'upperCol','X'})^2)^(1/2);
Vehicle.Chassis.SuspA1.Steer.Shaft_Lower = struct;
Vehicle.Chassis.SuspA1.Steer.Shaft_Lower.m = struct;
Vehicle.Chassis.SuspA1.Steer.Shaft_Lower.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Steer.Shaft_Lower.m.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Shaft_Lower.m.Value = 0.4;
Vehicle.Chassis.SuspA1.Steer.Pinion = struct;
Vehicle.Chassis.SuspA1.Steer.Pinion.xRad = struct;
Vehicle.Chassis.SuspA1.Steer.Pinion.xRad.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Pinion.xRad.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Pinion.xRad.Value = 0.015;
Vehicle.Chassis.SuspA1.Steer.Pinion.sMount = struct;
Vehicle.Chassis.SuspA1.Steer.Pinion.sMount.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Pinion.sMount.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Pinion.sMount.Value = ...
  hrdPt{'steerPinion',:}-[cos(pinionIncl)*Vehicle.Chassis.SuspA1.Steer.Pinion.xRad.Value,0,sin(pinionIncl)*Vehicle.Chassis.SuspA1.Steer.Pinion.xRad.Value];
Vehicle.Chassis.SuspA1.Steer.Pinion.m = struct;
Vehicle.Chassis.SuspA1.Steer.Pinion.m.Units = 'kg';
Vehicle.Chassis.SuspA1.Steer.Pinion.m.Comments = '';
Vehicle.Chassis.SuspA1.Steer.Pinion.m.Value = 0.05;
Vehicle.Chassis.SuspA1.Steer.Ratio_Table = struct;
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.aWheel = struct;
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.aWheel.Units = 'rad';
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.aWheel.Comments = ...
  'Wheel Angle - reference only -- Modify to get value form table';
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.aWheel.Value = linspace(-2.689,2.689,21);
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.xRack = struct;
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.xRack.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.xRack.Comments = ...
  'Rack Displacement - reference only--Modify to get value form table';
Vehicle.Chassis.SuspA1.Steer.Ratio_Table.xRack.Value = linspace(-0.035,0.035,21);
Vehicle.Chassis.SuspA1.Steer.Type = 'Steer';
Vehicle.Chassis.SuspA1.Steer.Instance = ...
  'WheelDrivenRack1UJoint_Ch2_Achilles';
Vehicle.Chassis.SuspA1.Steer.DriverHuman = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.class = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.class.Value = 'None';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.s = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.s.Units = 'm';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.s.Comments = '';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.s.Value = ...
  [-1.26656038245259 0.376762948446593 0.62577262194717];
Vehicle.Chassis.SuspA1.Steer.DriverHuman.a = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.a.Units = 'deg';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.a.Comments = ...
  'Roll-Pitch-Yaw, applied Y->P->R';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.a.Value = ...
  [0 0 0];
Vehicle.Chassis.SuspA1.Steer.DriverHuman.rho = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.rho.Units = 'kg/m^3';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.rho.Comments = ...
  'Use to adjust passenger mass';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.rho.Value = 1000;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.aHeadInclination = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.aHeadInclination.Units = 'deg';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.aHeadInclination.Comments = '';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.aHeadInclination.Value = 15;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Color = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Color.Units = '[RGB] (0-1)';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Color.Comments = '[RGB]';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Color.Value = ...
  [0.7921 0.8196 0.9333];
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Opacity = struct;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Opacity.Units = '(0-1)';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Opacity.Comments = '';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Opacity.Value = 1;
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Type = 'DriverHuman';
Vehicle.Chassis.SuspA1.Steer.DriverHuman.Instance = 'None';
clear hrdPt;
%% Rear Suspension
hrdPt=read_excel(filename,'HardpointsRr','UseRowNames',true)./1000;
hrdPt.X=hrdPt.X+1.575;
Vehicle.Chassis.SuspA2 = struct;
Vehicle.Chassis.SuspA2.Linkage = struct;
Vehicle.Chassis.SuspA2.Linkage.class = struct;
Vehicle.Chassis.SuspA2.Linkage.class.Value = 'DoubleWishbone Pushrod NoSteer';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone = struct;
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF = struct;
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardF.Value = ...
  hrdPt{'lcaF',:};
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR = struct;
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sInboardR.Value = ...
  hrdPt{'lcaR',:};
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard = struct;
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.sOutboard.Value = ...
  hrdPt{'lcaO',:};
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.m = struct;
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.m.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.m.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.LowerWishbone.m.Value = 0.3;
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone = struct;
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF = struct;
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardF.Value = ...
  hrdPt{'ucaF',:};
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR = struct;
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sInboardR.Value = ...
  hrdPt{'ucaR',:};
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard = struct;
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.sOutboard.Value = ...
  hrdPt{'ucaO',:};
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.m = struct;
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.m.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.m.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.UpperWishbone.m.Value = 0.2;
Vehicle.Chassis.SuspA2.Linkage.Upright = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.sCG = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.sCG.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Upright.sCG.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upright.sCG.Value = ...
  hrdPt{'uprightCG',:};
Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upright.sWheelCentre.Value = ...
  hrdPt{'wheelCenter',:};
Vehicle.Chassis.SuspA2.Linkage.Upright.m = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.m.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.Upright.m.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upright.m.Value = 1;
Vehicle.Chassis.SuspA2.Linkage.Upright.aToe = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.aToe.Units = 'deg';
Vehicle.Chassis.SuspA2.Linkage.Upright.aToe.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upright.aToe.Value = 0;
Vehicle.Chassis.SuspA2.Linkage.Upright.aCamber = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.aCamber.Units = 'deg';
Vehicle.Chassis.SuspA2.Linkage.Upright.aCamber.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upright.aCamber.Value = 0;
Vehicle.Chassis.SuspA2.Linkage.Upright.xAxle = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.xAxle.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Upright.xAxle.Comments = 'Axle length';
Vehicle.Chassis.SuspA2.Linkage.Upright.xAxle.Value = 0.15;
Vehicle.Chassis.SuspA2.Linkage.Upright.xWCtoBearing = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.xWCtoBearing.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Upright.xWCtoBearing.Comments = ...
  'Wheel Center to Bearing';
Vehicle.Chassis.SuspA2.Linkage.Upright.xWCtoBearing.Value = 0.05;
Vehicle.Chassis.SuspA2.Linkage.Upright.mAxle = struct;
Vehicle.Chassis.SuspA2.Linkage.Upright.mAxle.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.Upright.mAxle.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upright.mAxle.Value = 1.5;
Vehicle.Chassis.SuspA2.Linkage.TrackRod = struct;
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard = struct;
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sInboard.Value = ...
  hrdPt{'trackrodI',:};
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard = struct;
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.TrackRod.sOutboard.Value = ...
  hrdPt{'trackrodO',:};
Vehicle.Chassis.SuspA2.Linkage.TrackRod.m = struct;
Vehicle.Chassis.SuspA2.Linkage.TrackRod.m.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.TrackRod.m.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.TrackRod.m.Value = 0.2;
Vehicle.Chassis.SuspA2.Linkage.Steer = struct;
Vehicle.Chassis.SuspA2.Linkage.Steer.class = struct;
Vehicle.Chassis.SuspA2.Linkage.Steer.class.Value = 'Off';
Vehicle.Chassis.SuspA2.Linkage.Shock = struct;
Vehicle.Chassis.SuspA2.Linkage.Shock.sTop = struct;
Vehicle.Chassis.SuspA2.Linkage.Shock.sTop.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Shock.sTop.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Shock.sTop.Value = ...
  hrdPt{'shockT',:};
Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom = struct;
Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Shock.sBottom.Value = ...
  hrdPt{'shockB',:};
Vehicle.Chassis.SuspA2.Linkage.Shock.mPiston = struct;
Vehicle.Chassis.SuspA2.Linkage.Shock.mPiston.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.Shock.mPiston.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Shock.mPiston.Value = 0.8;
Vehicle.Chassis.SuspA2.Linkage.Shock.mCylinder = struct;
Vehicle.Chassis.SuspA2.Linkage.Shock.mCylinder.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.Shock.mCylinder.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Shock.mCylinder.Value = 1.2;
Vehicle.Chassis.SuspA2.Linkage.Endstop = struct;
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMax = struct;
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMax.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMax.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMax.Value = 0.0635/2;
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMin = struct;
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMin.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMin.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Endstop.xMin.Value = -0.0635/2;
%% Rear suspension Joint
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.class = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.class.Value = ...
  'Rigid_1Rev';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law.Comments = ...
  'Linear / Table /Maxwell SLS';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1 = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.k1.Value = 3013.9;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1 = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.b1.Value = 11471;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.x.Value = ...
  [-3 -1.5 1.5 3];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialSpring.Maxwell.f.Value = ...
  [-6555 -2622 2622 6555];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.RadialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.AxialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.Type = ...
  'Subframe_Conn';
Vehicle.Chassis.SuspA2.Linkage.Upper_Arm_to_Subframe.Instance = ...
  'Bushing_Sedan_UA';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.class = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.class.Value = ...
  'Rigid_1Rev';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law.Comments = ...
  'Linear / Table /Maxwell SLS';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1 = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.k1.Value = 3013.9;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1 = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.b1.Value = 11471;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.x.Value = ...
  [-3 -1.5 1.5 3];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialSpring.Maxwell.f.Value = ...
  [-6555 -2622 2622 6555];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.RadialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K.Units = ...
  'N/mm';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Linear.K.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x.Units = ...
  'mm';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.x.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialSpring.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law.Units = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law.Comments = ...
  'Linear / Table';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Law.Value = ...
  'Linear';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d.Units = ...
  'N/(m/s)';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Linear.d.Value = 2e4;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v.Units = ...
  'm/s';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.v.Value = ...
  [-4 -3 -2 -1 0 1 2 3 4];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f = struct;
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f.Units = 'N';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.AxialDamper.Table.f.Value = ...
  [-4000 -2750 -1500 -500 0 500 1500 2750 4000];
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.Type = ...
  'Subframe_Conn';
Vehicle.Chassis.SuspA2.Linkage.Lower_Arm_to_Subframe.Instance = ...
  'Bushing_Sedan_LA';
Vehicle.Chassis.SuspA2.Linkage.Pushrod = struct;
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sLowerArm = struct;
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sLowerArm.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sLowerArm.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sLowerArm.Value = ...
    hrdPt{'PushrodOut',:};
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sBellcrank = struct;
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sBellcrank.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sBellcrank.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Pushrod.sBellcrank.Value = ...
  hrdPt{'BCrod',:};
Vehicle.Chassis.SuspA2.Linkage.Pushrod.m = struct;
Vehicle.Chassis.SuspA2.Linkage.Pushrod.m.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.Pushrod.m.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Pushrod.m.Value = 0.2;
Vehicle.Chassis.SuspA2.Linkage.Bellcrank = struct;
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sPivot = struct;
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sPivot.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sPivot.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sPivot.Value = ...
  hrdPt{'BCpivot',:};
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sAntiRollBar = struct;
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sAntiRollBar.Units = 'm';
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sAntiRollBar.Comments = ...
  'Must be same as AntiRollBar.sSuspension';
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.sAntiRollBar.Value = ...
  hrdPt{'arbSus',:};
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.m = struct;
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.m.Units = 'kg';
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.m.Comments = '';
Vehicle.Chassis.SuspA2.Linkage.Bellcrank.m.Value = 0.55;
Vehicle.Chassis.SuspA2.Linkage.Type = 'Linkage';
Vehicle.Chassis.SuspA2.Linkage.Instance = ...
  'DoubleWishbonePushrod_FSAE_Achilles_f';
%% Antiroll bar Rear
ARBcoef=read_excel(filename, 'Suspension','UseRowNames',true);
Vehicle.Chassis.SuspA2.class = struct;
Vehicle.Chassis.SuspA2.class.Value = 'Linkage';
Vehicle.Chassis.SuspA2.AntiRollBar = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.class = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.class.Value = 'DroplinkRod';
Vehicle.Chassis.SuspA2.AntiRollBar.sSuspension = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.sSuspension.Units = 'm';
Vehicle.Chassis.SuspA2.AntiRollBar.sSuspension.Comments = '';
Vehicle.Chassis.SuspA2.AntiRollBar.sSuspension.Value = ...
  hrdPt{'arbSus',:};
Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard.Units = 'm';
Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard.Comments = '';
Vehicle.Chassis.SuspA2.AntiRollBar.sOutboard.Value = ...
  hrdPt{'arbO',:};
Vehicle.Chassis.SuspA2.AntiRollBar.sInboard = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.sInboard.Units = 'm';
Vehicle.Chassis.SuspA2.AntiRollBar.sInboard.Comments = '';
Vehicle.Chassis.SuspA2.AntiRollBar.sInboard.Value = ...
  hrdPt{'arbI',:};
Vehicle.Chassis.SuspA2.AntiRollBar.k = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.k.Units = 'N/rad';
Vehicle.Chassis.SuspA2.AntiRollBar.k.Comments = '';
Vehicle.Chassis.SuspA2.AntiRollBar.k.Value = ARBcoef{'Stiffness','Rear'};
Vehicle.Chassis.SuspA2.AntiRollBar.m = struct;
Vehicle.Chassis.SuspA2.AntiRollBar.m.Units = 'kg';
Vehicle.Chassis.SuspA2.AntiRollBar.m.Comments = '';
Vehicle.Chassis.SuspA2.AntiRollBar.m.Value = 0.7;
Vehicle.Chassis.SuspA2.AntiRollBar.Type = 'AntiRollBar';
Vehicle.Chassis.SuspA2.AntiRollBar.Instance = ...
  'Droplink_FSAE_Achilles_r';
Vehicle.Chassis.SuspA2.Steer = struct;
Vehicle.Chassis.SuspA2.Steer.class = struct;
Vehicle.Chassis.SuspA2.Steer.class.Value = 'None';
Vehicle.Chassis.SuspA2.Steer.Type = 'Steer';
Vehicle.Chassis.SuspA2.Steer.Instance = 'None_default';
clear hrdPt ARBcoef;
%% Aero
Vehicle.Chassis.Aero = struct;
Vehicle.Chassis.Aero.class = struct;
Vehicle.Chassis.Aero.class.Value = 'sedan';
Vehicle.Chassis.Aero.CL = struct;
Vehicle.Chassis.Aero.CL.Units = '';
Vehicle.Chassis.Aero.CL.Comments = 'Positive for upward lift';
Vehicle.Chassis.Aero.CL.Value = -3;
Vehicle.Chassis.Aero.CD = struct;
Vehicle.Chassis.Aero.CD.Units = '';
Vehicle.Chassis.Aero.CD.Comments = '';
Vehicle.Chassis.Aero.CD.Value = -1.8;
Vehicle.Chassis.Aero.rho_air = struct;
Vehicle.Chassis.Aero.rho_air.Units = 'kg/m^3';
Vehicle.Chassis.Aero.rho_air.Comments = '';
Vehicle.Chassis.Aero.rho_air.Value = 1.225;
Vehicle.Chassis.Aero.ARef = struct;
Vehicle.Chassis.Aero.ARef.Units = 'm^2';
Vehicle.Chassis.Aero.ARef.Comments = '';
Vehicle.Chassis.Aero.ARef.Value = 1.2;
Vehicle.Chassis.Aero.sPressureCentre = struct;
Vehicle.Chassis.Aero.sPressureCentre.Units = 'm';
Vehicle.Chassis.Aero.sPressureCentre.Comments = '';
Vehicle.Chassis.Aero.sPressureCentre.Value = ...
  [-0.8 0 0.26];
Vehicle.Chassis.Aero.Type = 'Aero';
Vehicle.Chassis.Aero.Instance = 'FSAE_Achilles';
%% Shock
coef=read_excel(filename,'Suspension','UseRowNames',true);

Vehicle.Chassis.Spring = struct;
Vehicle.Chassis.Spring.class = struct;
Vehicle.Chassis.Spring.class.Value = 'Independent';
Vehicle.Chassis.Spring.Axle1 = struct;
Vehicle.Chassis.Spring.Axle1.class = struct;
Vehicle.Chassis.Spring.Axle1.class.Value = 'Linear';
Vehicle.Chassis.Spring.Axle1.K = struct;
Vehicle.Chassis.Spring.Axle1.K.Units = 'N/m';
Vehicle.Chassis.Spring.Axle1.K.Comments = '';
Vehicle.Chassis.Spring.Axle1.K.Value = coef{'Rate','Front'};
Vehicle.Chassis.Spring.Axle1.xPreload = struct;
Vehicle.Chassis.Spring.Axle1.xPreload.Units = 'm';
Vehicle.Chassis.Spring.Axle1.xPreload.Comments = '';
Vehicle.Chassis.Spring.Axle1.xPreload.Value = coef{'Preload','Front'}+0.00559;
Vehicle.Chassis.Spring.Axle1.Type = 'Spring';
Vehicle.Chassis.Spring.Axle1.Instance = 'FSAE_Achilles_DW_Linear_A1';
Vehicle.Chassis.Spring.Axle2 = struct;
Vehicle.Chassis.Spring.Axle2.class = struct;
Vehicle.Chassis.Spring.Axle2.class.Value = 'Linear';
Vehicle.Chassis.Spring.Axle2.K = struct;
Vehicle.Chassis.Spring.Axle2.K.Units = 'N/m';
Vehicle.Chassis.Spring.Axle2.K.Comments = '';
Vehicle.Chassis.Spring.Axle2.K.Value = coef{'Rate','Rear'};
Vehicle.Chassis.Spring.Axle2.xPreload = struct;
Vehicle.Chassis.Spring.Axle2.xPreload.Units = 'm';
Vehicle.Chassis.Spring.Axle2.xPreload.Comments = '';
Vehicle.Chassis.Spring.Axle2.xPreload.Value = coef{'Preload','Rear'}+0.0039;
Vehicle.Chassis.Spring.Axle2.Type = 'Spring';
Vehicle.Chassis.Spring.Axle2.Instance = 'FSAE_Achilles_DW_Linear_A2';
Vehicle.Chassis.Spring.Type = 'Springs';
Vehicle.Chassis.Spring.Instance = 'Axle2_Independent';
Vehicle.Chassis.Damper = struct;
Vehicle.Chassis.Damper.class = struct;
Vehicle.Chassis.Damper.class.Value = 'Independent';
Vehicle.Chassis.Damper.Axle1 = struct;
Vehicle.Chassis.Damper.Axle1.class = struct;
Vehicle.Chassis.Damper.Axle1.class.Value = 'Linear';
Vehicle.Chassis.Damper.Axle1.Damping = struct;
Vehicle.Chassis.Damper.Axle1.Damping.d = struct;
Vehicle.Chassis.Damper.Axle1.Damping.d.Units = 'N/(m/s)';
Vehicle.Chassis.Damper.Axle1.Damping.d.Comments = '';
Vehicle.Chassis.Damper.Axle1.Damping.d.Value = coef{'Damping','Front'};
Vehicle.Chassis.Damper.Axle1.Endstop = struct;
Vehicle.Chassis.Damper.Axle1.Endstop.KxMax = struct;
Vehicle.Chassis.Damper.Axle1.Endstop.KxMax.Units = 'N/m';
Vehicle.Chassis.Damper.Axle1.Endstop.KxMax.Comments = '';
Vehicle.Chassis.Damper.Axle1.Endstop.KxMax.Value = 1.0E+6;
Vehicle.Chassis.Damper.Axle1.Endstop.KxMin = struct;
Vehicle.Chassis.Damper.Axle1.Endstop.KxMin.Units = 'N/m';
Vehicle.Chassis.Damper.Axle1.Endstop.KxMin.Comments = '';
Vehicle.Chassis.Damper.Axle1.Endstop.KxMin.Value = 1.0E+6;
Vehicle.Chassis.Damper.Axle1.Endstop.dxMax = struct;
Vehicle.Chassis.Damper.Axle1.Endstop.dxMax.Units = 'N/m';
Vehicle.Chassis.Damper.Axle1.Endstop.dxMax.Comments = '';
Vehicle.Chassis.Damper.Axle1.Endstop.dxMax.Value = 150;
Vehicle.Chassis.Damper.Axle1.Endstop.dxMin = struct;
Vehicle.Chassis.Damper.Axle1.Endstop.dxMin.Units = 'N/m';
Vehicle.Chassis.Damper.Axle1.Endstop.dxMin.Comments = '';
Vehicle.Chassis.Damper.Axle1.Endstop.dxMin.Value = 150;
Vehicle.Chassis.Damper.Axle1.Endstop.xTransition = struct;
Vehicle.Chassis.Damper.Axle1.Endstop.xTransition.Units = 'm';
Vehicle.Chassis.Damper.Axle1.Endstop.xTransition.Comments = '';
Vehicle.Chassis.Damper.Axle1.Endstop.xTransition.Value = 0.0001;
Vehicle.Chassis.Damper.Axle1.Type = 'Damper';
Vehicle.Chassis.Damper.Axle1.Instance = 'FSAE_Achilles_DW_Linear_A1';
Vehicle.Chassis.Damper.Axle2 = struct;
Vehicle.Chassis.Damper.Axle2.class = struct;
Vehicle.Chassis.Damper.Axle2.class.Value = 'Linear';
Vehicle.Chassis.Damper.Axle2.Damping = struct;
Vehicle.Chassis.Damper.Axle2.Damping.d = struct;
Vehicle.Chassis.Damper.Axle2.Damping.d.Units = 'N/(m/s)';
Vehicle.Chassis.Damper.Axle2.Damping.d.Comments = '';
Vehicle.Chassis.Damper.Axle2.Damping.d.Value = coef{'Damping','Rear'};
Vehicle.Chassis.Damper.Axle2.Endstop = struct;
Vehicle.Chassis.Damper.Axle2.Endstop.KxMax = struct;
Vehicle.Chassis.Damper.Axle2.Endstop.KxMax.Units = 'N/m';
Vehicle.Chassis.Damper.Axle2.Endstop.KxMax.Comments = '';
Vehicle.Chassis.Damper.Axle2.Endstop.KxMax.Value = 1.0E+6;
Vehicle.Chassis.Damper.Axle2.Endstop.KxMin = struct;
Vehicle.Chassis.Damper.Axle2.Endstop.KxMin.Units = 'N/m';
Vehicle.Chassis.Damper.Axle2.Endstop.KxMin.Comments = '';
Vehicle.Chassis.Damper.Axle2.Endstop.KxMin.Value = 1.0E+6;
Vehicle.Chassis.Damper.Axle2.Endstop.dxMax = struct;
Vehicle.Chassis.Damper.Axle2.Endstop.dxMax.Units = 'N/m';
Vehicle.Chassis.Damper.Axle2.Endstop.dxMax.Comments = '';
Vehicle.Chassis.Damper.Axle2.Endstop.dxMax.Value = 150;
Vehicle.Chassis.Damper.Axle2.Endstop.dxMin = struct;
Vehicle.Chassis.Damper.Axle2.Endstop.dxMin.Units = 'N/m';
Vehicle.Chassis.Damper.Axle2.Endstop.dxMin.Comments = '';
Vehicle.Chassis.Damper.Axle2.Endstop.dxMin.Value = 150;
Vehicle.Chassis.Damper.Axle2.Endstop.xTransition = struct;
Vehicle.Chassis.Damper.Axle2.Endstop.xTransition.Units = 'm';
Vehicle.Chassis.Damper.Axle2.Endstop.xTransition.Comments = '';
Vehicle.Chassis.Damper.Axle2.Endstop.xTransition.Value = 0.0001;
Vehicle.Chassis.Damper.Axle2.Type = 'Damper';
Vehicle.Chassis.Damper.Axle2.Instance = 'FSAE_Achilles_DW_Linear_A2';
Vehicle.Chassis.Damper.Type = 'Dampers';
Vehicle.Chassis.Damper.Instance = 'Axle2_Independent';
clear coef;
%% Tire 
Vehicle.Chassis.Tire = struct;
Vehicle.Chassis.Tire.class = struct;
Vehicle.Chassis.Tire.class.Value = 'MFMbody';
Vehicle.Chassis.Tire.tirFile = struct;
Vehicle.Chassis.Tire.tirFile.Units = '';
Vehicle.Chassis.Tire.tirFile.Comments = '';
Vehicle.Chassis.Tire.tirFile.Value = 'which(''Hoosier_20p5x7_13_R20.tir'')';
Vehicle.Chassis.Tire.Mass = struct;
Vehicle.Chassis.Tire.Mass.Units = '';
Vehicle.Chassis.Tire.Mass.Comments = '';
Vehicle.Chassis.Tire.Mass.Value = 10;
Vehicle.Chassis.Tire.Inertia = struct;
Vehicle.Chassis.Tire.Inertia.Units = '';
Vehicle.Chassis.Tire.Inertia.Comments = '';
Vehicle.Chassis.Tire.Inertia.Value = ...
  [1 2];
Vehicle.Chassis.Tire.roadFile = struct;
Vehicle.Chassis.Tire.roadFile.Units = '';
Vehicle.Chassis.Tire.roadFile.Comments = '';
Vehicle.Chassis.Tire.roadFile.Value = 'which(''TNO_FlatRoad.rdf'')';
Vehicle.Chassis.Tire.CornerringStiffnes = struct;
Vehicle.Chassis.Tire.CornerringStiffnes.Units = 'N/rad';
Vehicle.Chassis.Tire.CornerringStiffnes.Comments = 'Value taken manually from the excel';
Vehicle.Chassis.Tire.CornerringStiffnes.Value = 25000;
Vehicle.Chassis.Tire.fContactPoint = struct;
Vehicle.Chassis.Tire.fContactPoint.Units = 'sec';
Vehicle.Chassis.Tire.fContactPoint.Comments = ...
  ['Break algebraic loop between tire center position and contact point' ...
   ' position and orientation'];
Vehicle.Chassis.Tire.fContactPoint.Value = 0.01;
Vehicle.Chassis.Tire.Type = 'Tire';
Vehicle.Chassis.Tire.Instance = 'MFMbody_190_50R10';
Vehicle.Chassis.Tire.TireBody = struct;
Vehicle.Chassis.Tire.TireBody.class = struct;
Vehicle.Chassis.Tire.TireBody.class.Value = 'Parameterized';
Vehicle.Chassis.Tire.TireBody.sOffset = struct;
Vehicle.Chassis.Tire.TireBody.sOffset.Units = 'm';
Vehicle.Chassis.Tire.TireBody.sOffset.Comments = '';
Vehicle.Chassis.Tire.TireBody.sOffset.Value = ...
  [0 0 0];
Vehicle.Chassis.Tire.TireBody.Type = 'TireBody';
Vehicle.Chassis.Tire.TireBody.Instance = 'Parameterized';
Vehicle.Chassis.TireA2 = struct;
Vehicle.Chassis.TireA2.class = struct;
Vehicle.Chassis.TireA2.class.Value = 'MFMbody';
Vehicle.Chassis.TireA2.tirFile = struct;
Vehicle.Chassis.TireA2.tirFile.Units = '';
Vehicle.Chassis.TireA2.tirFile.Comments = '';
Vehicle.Chassis.TireA2.tirFile.Value = 'which(''Hoosier_20p5x7_13_R20.tir'')';
Vehicle.Chassis.TireA2.Mass = struct;
Vehicle.Chassis.TireA2.Mass.Units = '';
Vehicle.Chassis.TireA2.Mass.Comments = '';
Vehicle.Chassis.TireA2.Mass.Value = 10;
Vehicle.Chassis.TireA2.Inertia = struct;
Vehicle.Chassis.TireA2.Inertia.Units = '';
Vehicle.Chassis.TireA2.Inertia.Comments = '';
Vehicle.Chassis.TireA2.Inertia.Value = ...
  [1 2];
Vehicle.Chassis.TireA2.roadFile = struct;
Vehicle.Chassis.TireA2.roadFile.Units = '';
Vehicle.Chassis.TireA2.roadFile.Comments = '';
Vehicle.Chassis.TireA2.roadFile.Value = 'which(''TNO_FlatRoad.rdf'')';
Vehicle.Chassis.TireA2.CornerringStiffnes = struct;
Vehicle.Chassis.TireA2.CornerringStiffnes.Units = 'N/rad';
Vehicle.Chassis.TireA2.CornerringStiffnes.Comments = 'Value taken manually from the excel';
Vehicle.Chassis.TireA2.CornerringStiffnes.Value = 27000;

Vehicle.Chassis.TireA2.fContactPoint = struct;
Vehicle.Chassis.TireA2.fContactPoint.Units = 'sec';
Vehicle.Chassis.TireA2.fContactPoint.Comments = ...
  ['Break algebraic loop between tire center position and contact point' ...
   ' position and orientation'];
Vehicle.Chassis.TireA2.fContactPoint.Value = 0.01;
Vehicle.Chassis.TireA2.Type = 'Tire';
Vehicle.Chassis.TireA2.Instance = 'MFMbody_190_50R10';
Vehicle.Chassis.TireA2.TireBody = struct;
Vehicle.Chassis.TireA2.TireBody.class = struct;
Vehicle.Chassis.TireA2.TireBody.class.Value = 'Parameterized';
Vehicle.Chassis.TireA2.TireBody.sOffset = struct;
Vehicle.Chassis.TireA2.TireBody.sOffset.Units = 'm';
Vehicle.Chassis.TireA2.TireBody.sOffset.Comments = '';
Vehicle.Chassis.TireA2.TireBody.sOffset.Value = ...
  [0 0 0];
Vehicle.Chassis.TireA2.TireBody.Type = 'TireBody';
Vehicle.Chassis.TireA2.TireBody.Instance = 'Parameterized';
Vehicle.config = 'Achilles_DWishbone';
Vehicle.Powertrain = struct;
Vehicle.Powertrain.Power = struct;
Vehicle.Powertrain.Power.class = struct;
Vehicle.Powertrain.Power.class.Value = 'Electric_L2_R2';
%% Cooling
Vehicle.Powertrain.Power.Cooling = struct;
Vehicle.Powertrain.Power.Cooling.class = struct;
Vehicle.Powertrain.Power.Cooling.class.Value = 'Liquid_Loop1';
Vehicle.Powertrain.Power.TAmbient = struct;
Vehicle.Powertrain.Power.TAmbient.Units = 'K';
Vehicle.Powertrain.Power.TAmbient.Comments = 'Temperature';
Vehicle.Powertrain.Power.TAmbient.Value = 293;

%% Motors
filename='ARTTU.xlsx';
motor_data=read_excel(filename,'Motor');
Vehicle.Powertrain.Power.Motor = struct;
Vehicle.Powertrain.Power.Motor.TorqueConstant = struct;
Vehicle.Powertrain.Power.Motor.TorqueConstant.Units = 'N*m/A';
Vehicle.Powertrain.Power.Motor.TorqueConstant.Comments = 'only 220V value';
Vehicle.Powertrain.Power.Motor.TorqueConstant.Value = 0.4839;
Vehicle.Powertrain.Power.Motor.TorqueSpd = struct;
Vehicle.Powertrain.Power.Motor.TorqueSpd.w = struct;
Vehicle.Powertrain.Power.Motor.TorqueSpd.w.Units = 'rpm';
Vehicle.Powertrain.Power.Motor.TorqueSpd.w.Comments = '';
Vehicle.Powertrain.Power.Motor.TorqueSpd.w.Value = motor_data.EngineSpeed_rpm_;
Vehicle.Powertrain.Power.Motor.TorqueSpd.trq = struct;
Vehicle.Powertrain.Power.Motor.TorqueSpd.trq.Units = 'N*m';
Vehicle.Powertrain.Power.Motor.TorqueSpd.trq.Comments = '';
Vehicle.Powertrain.Power.Motor.TorqueSpd.trq.Value = motor_data.Torque_Nm_;
Vehicle.Powertrain.Power.Motor.fActuatorCutoff = struct;
Vehicle.Powertrain.Power.Motor.fActuatorCutoff.Units = 'Hz';
Vehicle.Powertrain.Power.Motor.fActuatorCutoff.Comments = '';
Vehicle.Powertrain.Power.Motor.fActuatorCutoff.Value = 50;
Vehicle.Powertrain.Power.Motor.LossTable = struct;
Vehicle.Powertrain.Power.Motor.LossTable.w = struct;
Vehicle.Powertrain.Power.Motor.LossTable.w.Units = 'rpm';
Vehicle.Powertrain.Power.Motor.LossTable.w.Comments = '';
Vehicle.Powertrain.Power.Motor.LossTable.w.Value = ...
  [0 1666.6667 3333.3333 4774.6371 5000 6666.6667 8333.3333 10000 11666.6667 ...
   13333.3333 15000 16666.6667 18333.3333 20000];
Vehicle.Powertrain.Power.Motor.LossTable.trq = struct;
Vehicle.Powertrain.Power.Motor.LossTable.trq.Units = 'N*m';
Vehicle.Powertrain.Power.Motor.LossTable.trq.Comments = '';
Vehicle.Powertrain.Power.Motor.LossTable.trq.Value = ...
  [0 20 40 60 80 100 120 140 160 180 200];
Vehicle.Powertrain.Power.Motor.LossTable.efficiency = struct;
Vehicle.Powertrain.Power.Motor.LossTable.efficiency.Units = '';
Vehicle.Powertrain.Power.Motor.LossTable.efficiency.Comments = '';
Vehicle.Powertrain.Power.Motor.LossTable.efficiency.Value = ...
  [85 85 85 85 85 85 85 85 85 85 85;
   85 85 90 90 90 90 90 90 90 90 88;
   85 85 92 92 92 92 92 92 92 92 92;
   85 85 92 92 93 93 93 93 92 92 92;
   85 85 93 94 94 94 94 94 94 94 94;
   85 85 93 94 94 95 95 95 95 95 95;
   85 85 93 94 94 95 95 95 95 95 95;
   85 85 93 94 95 95 95 95 95 95 95;
   85 85 93 94 95 95 95 95 95 95 95;
   85 85 93 94 94 94 94 94 94 94 94;
   85 85 90 92 93 93 93 93 93 93 93;
   85 85 90 92 93 93 93 93 93 93 93;
   85 85 90 92 93 93 93 93 93 93 93;
   85 85 90 92 93 93 93 93 93 93 93];
Vehicle.Powertrain.Power.Motor.ThermalLoss = struct;
Vehicle.Powertrain.Power.Motor.ThermalLoss.T1 = struct;
Vehicle.Powertrain.Power.Motor.ThermalLoss.T1.Units = 'degC';
Vehicle.Powertrain.Power.Motor.ThermalLoss.T1.Comments = '';
Vehicle.Powertrain.Power.Motor.ThermalLoss.T1.Value = 25;
Vehicle.Powertrain.Power.Motor.ThermalLoss.T2 = struct;
Vehicle.Powertrain.Power.Motor.ThermalLoss.T2.Units = 'degC';
Vehicle.Powertrain.Power.Motor.ThermalLoss.T2.Comments = '';
Vehicle.Powertrain.Power.Motor.ThermalLoss.T2.Value = 100;
Vehicle.Powertrain.Power.Motor.ThermalLoss.efficiency = struct;
Vehicle.Powertrain.Power.Motor.ThermalLoss.efficiency.Units = '';
Vehicle.Powertrain.Power.Motor.ThermalLoss.efficiency.Comments = '';
Vehicle.Powertrain.Power.Motor.ThermalLoss.efficiency.Value = ...
  [90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90];
Vehicle.Powertrain.Power.Motor.ThermalLoss.mThermal = struct;
Vehicle.Powertrain.Power.Motor.ThermalLoss.mThermal.Units = 'J/K';
Vehicle.Powertrain.Power.Motor.ThermalLoss.mThermal.Comments = '';
Vehicle.Powertrain.Power.Motor.ThermalLoss.mThermal.Value = 800;
Vehicle.Powertrain.Power.Motor.ThermalLoss.Tinit = struct;
Vehicle.Powertrain.Power.Motor.ThermalLoss.Tinit.Units = 'degK';
Vehicle.Powertrain.Power.Motor.ThermalLoss.Tinit.Comments = '';
Vehicle.Powertrain.Power.Motor.ThermalLoss.Tinit.Value = 300;
Vehicle.Powertrain.Power.Motor.J = struct;
Vehicle.Powertrain.Power.Motor.J.Units = 'kg*m^2';
Vehicle.Powertrain.Power.Motor.J.Comments = ...
  'Must be 0 for fast initialization';
Vehicle.Powertrain.Power.Motor.J.Value = 0;
Vehicle.Powertrain.Power.MotorR2 = struct;
Vehicle.Powertrain.Power.MotorR2.TorqueSpd = struct;
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.w = struct;
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.w.Units = 'rpm';
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.w.Comments = '';
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.w.Value = motor_data.EngineSpeed_rpm_;
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.trq = struct;
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.trq.Units = 'N*m';
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.trq.Comments = '';
Vehicle.Powertrain.Power.MotorR2.TorqueSpd.trq.Value = motor_data.Torque_Nm_;
Vehicle.Powertrain.Power.MotorR2.fActuatorCutoff = struct;
Vehicle.Powertrain.Power.MotorR2.fActuatorCutoff.Units = 'Hz';
Vehicle.Powertrain.Power.MotorR2.fActuatorCutoff.Comments = '';
Vehicle.Powertrain.Power.MotorR2.fActuatorCutoff.Value = 50;
Vehicle.Powertrain.Power.MotorR2.LossTable = struct;
Vehicle.Powertrain.Power.MotorR2.LossTable.w = struct;
Vehicle.Powertrain.Power.MotorR2.LossTable.w.Units = 'rpm';
Vehicle.Powertrain.Power.MotorR2.LossTable.w.Comments = '';
Vehicle.Powertrain.Power.MotorR2.LossTable.w.Value = ...
  [0 1666.6667 3333.3333 4774.6371 5000 6666.6667 8333.3333 10000 11666.6667 ...
   13333.3333 15000 16666.6667 18333.3333 20000];
Vehicle.Powertrain.Power.MotorR2.LossTable.trq = struct;
Vehicle.Powertrain.Power.MotorR2.LossTable.trq.Units = 'N*m';
Vehicle.Powertrain.Power.MotorR2.LossTable.trq.Comments = '';
Vehicle.Powertrain.Power.MotorR2.LossTable.trq.Value = ...
  [0 20 40 60 80 100 120 140 160 180 200];
Vehicle.Powertrain.Power.MotorR2.LossTable.efficiency = struct;
Vehicle.Powertrain.Power.MotorR2.LossTable.efficiency.Units = '';
Vehicle.Powertrain.Power.MotorR2.LossTable.efficiency.Comments = '';
Vehicle.Powertrain.Power.MotorR2.LossTable.efficiency.Value = ...
  [85 85 85 85 85 85 85 85 85 85 85;
   85 85 90 90 90 90 90 90 90 90 88;
   85 85 92 92 92 92 92 92 92 92 92;
   85 85 92 92 93 93 93 93 92 92 92;
   85 85 93 94 94 94 94 94 94 94 94;
   85 85 93 94 94 95 95 95 95 95 95;
   85 85 93 94 94 95 95 95 95 95 95;
   85 85 93 94 95 95 95 95 95 95 95;
   85 85 93 94 95 95 95 95 95 95 95;
   85 85 93 94 94 94 94 94 94 94 94;
   85 85 90 92 93 93 93 93 93 93 93;
   85 85 90 92 93 93 93 93 93 93 93;
   85 85 90 92 93 93 93 93 93 93 93;
   85 85 90 92 93 93 93 93 93 93 93];
Vehicle.Powertrain.Power.MotorR2.ThermalLoss = struct;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T1 = struct;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T1.Units = 'degC';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T1.Comments = '';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T1.Value = 25;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T2 = struct;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T2.Units = 'degC';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T2.Comments = '';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.T2.Value = 100;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.efficiency = struct;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.efficiency.Units = '';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.efficiency.Comments = '';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.efficiency.Value = ...
  [90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90;
   90 90 90 90 90 90 90 90 90 90 90];
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.mThermal = struct;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.mThermal.Units = 'J/K';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.mThermal.Comments = '';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.mThermal.Value = 800;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.Tinit = struct;
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.Tinit.Units = 'degK';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.Tinit.Comments = '';
Vehicle.Powertrain.Power.MotorR2.ThermalLoss.Tinit.Value = 300;
Vehicle.Powertrain.Power.MotorR2.J = struct;
Vehicle.Powertrain.Power.MotorR2.J.Units = 'kg*m^2';
Vehicle.Powertrain.Power.MotorR2.J.Comments = ...
  'Must be 0 for fast initialization';
Vehicle.Powertrain.Power.MotorR2.J.Value = 0;
clear motor_data;

%% Electrical
Vehicle.Powertrain.Power.Converter = struct;
Vehicle.Powertrain.Power.Converter.vRef = struct;
Vehicle.Powertrain.Power.Converter.vRef.Units = 'V';
Vehicle.Powertrain.Power.Converter.vRef.Comments = '';
Vehicle.Powertrain.Power.Converter.vRef.Value = 650;
Vehicle.Powertrain.Power.Converter.Power = struct;
Vehicle.Powertrain.Power.Converter.Power.Units = 'W';
Vehicle.Powertrain.Power.Converter.Power.Comments = '';
Vehicle.Powertrain.Power.Converter.Power.Value = 60000;
Vehicle.Powertrain.Power.Converter.iMaxSupply = struct;
Vehicle.Powertrain.Power.Converter.iMaxSupply.Units = 'A';
Vehicle.Powertrain.Power.Converter.iMaxSupply.Comments = '';
Vehicle.Powertrain.Power.Converter.iMaxSupply.Value = 9230.76923076923;
Vehicle.Powertrain.Power.Converter.efficiency = struct;
Vehicle.Powertrain.Power.Converter.efficiency.Units = '';
Vehicle.Powertrain.Power.Converter.efficiency.Comments = '';
Vehicle.Powertrain.Power.Converter.efficiency.Value = 98;
Vehicle.Powertrain.Power.Converter.fConverter = struct;
Vehicle.Powertrain.Power.Converter.fConverter.Units = 'Hz';
Vehicle.Powertrain.Power.Converter.fConverter.Comments = '';
Vehicle.Powertrain.Power.Converter.fConverter.Value = 1000;
Vehicle.Powertrain.Power.Battery = struct;
Vehicle.Powertrain.Power.Battery.vNoLoad = struct;
Vehicle.Powertrain.Power.Battery.vNoLoad.SOC = struct;
Vehicle.Powertrain.Power.Battery.vNoLoad.SOC.Units = '';
Vehicle.Powertrain.Power.Battery.vNoLoad.SOC.Comments = '';
Vehicle.Powertrain.Power.Battery.vNoLoad.SOC.Value = ...
  [0 0.2 0.4 0.6 0.8 1];
Vehicle.Powertrain.Power.Battery.vNoLoad.T = struct;
Vehicle.Powertrain.Power.Battery.vNoLoad.T.Units = 'degK';
Vehicle.Powertrain.Power.Battery.vNoLoad.T.Comments = '';
Vehicle.Powertrain.Power.Battery.vNoLoad.T.Value = ...
  [243.1 253.1 263.1 273.1 283.1 298.1 313.1];
Vehicle.Powertrain.Power.Battery.vNoLoad.V0 = struct;
Vehicle.Powertrain.Power.Battery.vNoLoad.V0.Units = '';
Vehicle.Powertrain.Power.Battery.vNoLoad.V0.Comments = '';
Vehicle.Powertrain.Power.Battery.vNoLoad.V0.Value = ...
  [201.6 201.6 201.6 201.6 201.6 201.6 201.6;
   258.768 258.768 258.768 258.768 258.768 258.768 258.768;
   264.96 264.96 264.96 264.96 264.96 264.96 264.96;
   272.952 272.952 272.952 272.952 272.952 272.952 272.952;
   286.128 286.128 286.128 286.128 286.128 286.128 286.128;
   303.912 303.912 303.912 303.912 303.912 303.912 303.912];
Vehicle.Powertrain.Power.Battery.rTerminal = struct;
Vehicle.Powertrain.Power.Battery.rTerminal.SOC = struct;
Vehicle.Powertrain.Power.Battery.rTerminal.SOC.Units = '';
Vehicle.Powertrain.Power.Battery.rTerminal.SOC.Comments = '';
Vehicle.Powertrain.Power.Battery.rTerminal.SOC.Value = ...
  [0 0.2 0.4 0.6 0.8 1];
Vehicle.Powertrain.Power.Battery.rTerminal.T = struct;
Vehicle.Powertrain.Power.Battery.rTerminal.T.Units = 'degK';
Vehicle.Powertrain.Power.Battery.rTerminal.T.Comments = '';
Vehicle.Powertrain.Power.Battery.rTerminal.T.Value = ...
  [243.1 253.1 263.1 273.1 283.1 298.1 313.1];
Vehicle.Powertrain.Power.Battery.rTerminal.R0 = struct;
Vehicle.Powertrain.Power.Battery.rTerminal.R0.Units = '';
Vehicle.Powertrain.Power.Battery.rTerminal.R0.Comments = '';
Vehicle.Powertrain.Power.Battery.rTerminal.R0.Value = ...
  [0.31846 0.23 0.1571 0.073116 0.051948 0.020171 0.037008;
   0.33548 0.23594 0.14764 0.092268 0.0657 0.025891 0.048168;
   0.32497 0.19991 0.14616 0.091152 0.06462 0.024793 0.036;
   0.30492 0.1989 0.12427 0.08856 0.064008 0.027205 0.055296;
   0.37152 0.21755 0.13846 0.097776 0.069264 0.026478 0.055656;
   0.47304 0.28098 0.16261 0.10969 0.080424 0.036504 0.1004];
Vehicle.Powertrain.Power.Battery.AhTable = struct;
Vehicle.Powertrain.Power.Battery.AhTable.T = struct;
Vehicle.Powertrain.Power.Battery.AhTable.T.Units = 'degK';
Vehicle.Powertrain.Power.Battery.AhTable.T.Comments = '';
Vehicle.Powertrain.Power.Battery.AhTable.T.Value = ...
  [243.1 253.1 263.1 273.1 283.1 298.1 313.1];
Vehicle.Powertrain.Power.Battery.AhTable.Ah = struct;
Vehicle.Powertrain.Power.Battery.AhTable.Ah.Units = 'hr*A';
Vehicle.Powertrain.Power.Battery.AhTable.Ah.Comments = '';
Vehicle.Powertrain.Power.Battery.AhTable.Ah.Value = ...
  [230 230 230 230 230 230 230];
Vehicle.Powertrain.Power.Battery.SOCInit = struct;
Vehicle.Powertrain.Power.Battery.SOCInit.Units = '0-1';
Vehicle.Powertrain.Power.Battery.SOCInit.Comments = '';
Vehicle.Powertrain.Power.Battery.SOCInit.Value = 0.8;
Vehicle.Powertrain.Power.Type = 'Power';
Vehicle.Powertrain.Power.Instance = 'Electric_L1_R1_L2_R2_default';

%% Transmission
Vehicle.Powertrain.Driveline = struct;
Vehicle.Powertrain.Driveline.class = struct;
Vehicle.Powertrain.Driveline.class.Value = 'L2_R2';
Vehicle.Powertrain.Driveline.GearboxL2 = struct;
Vehicle.Powertrain.Driveline.GearboxL2.ratio = struct;
Vehicle.Powertrain.Driveline.GearboxL2.ratio.Units = '';
Vehicle.Powertrain.Driveline.GearboxL2.ratio.Comments = ...
  'Final Drive Ratio';
Vehicle.Powertrain.Driveline.GearboxL2.ratio.Value = 5;
Vehicle.Powertrain.Driveline.DriveshaftL2 = struct;
Vehicle.Powertrain.Driveline.DriveshaftL2.Units = '';
Vehicle.Powertrain.Driveline.DriveshaftL2.Comments = '';
Vehicle.Powertrain.Driveline.DriveshaftL2.Value = 'Driveshaft';
Vehicle.Powertrain.Driveline.GearboxR2 = struct;
Vehicle.Powertrain.Driveline.GearboxR2.ratio = struct;
Vehicle.Powertrain.Driveline.GearboxR2.ratio.Units = '';
Vehicle.Powertrain.Driveline.GearboxR2.ratio.Comments = ...
  'Final Drive Ratio';
Vehicle.Powertrain.Driveline.GearboxR2.ratio.Value = 5;
Vehicle.Powertrain.Driveline.DriveshaftR2 = struct;
Vehicle.Powertrain.Driveline.DriveshaftR2.Units = '';
Vehicle.Powertrain.Driveline.DriveshaftR2.Comments = '';
Vehicle.Powertrain.Driveline.DriveshaftR2.Value = 'Driveshaft';
Vehicle.Powertrain.Driveline.Type = 'Driveline';
Vehicle.Powertrain.Driveline.Instance = 'Axle2_L2_R2_default';
%% Brakes
Vehicle.Brakes = struct;
Vehicle.Brakes.class = struct;
Vehicle.Brakes.class.Value = 'PedalAbstract_DiscDisc';
Vehicle.Brakes.Axle1 = struct;
Vehicle.Brakes.Axle1.DiscAndPad = struct;
Vehicle.Brakes.Axle1.DiscAndPad.lMeanRadius = struct;
Vehicle.Brakes.Axle1.DiscAndPad.lMeanRadius.Units = 'm';
Vehicle.Brakes.Axle1.DiscAndPad.lMeanRadius.Comments = '';
Vehicle.Brakes.Axle1.DiscAndPad.lMeanRadius.Value = 0.15;
Vehicle.Brakes.Axle1.DiscAndPad.rMuStatic = struct;
Vehicle.Brakes.Axle1.DiscAndPad.rMuStatic.Units = '';
Vehicle.Brakes.Axle1.DiscAndPad.rMuStatic.Comments = '(0-1)';
Vehicle.Brakes.Axle1.DiscAndPad.rMuStatic.Value = 0.7;
Vehicle.Brakes.Axle1.DiscAndPad.rMuKinetic = struct;
Vehicle.Brakes.Axle1.DiscAndPad.rMuKinetic.Units = '';
Vehicle.Brakes.Axle1.DiscAndPad.rMuKinetic.Comments = '(0-1)';
Vehicle.Brakes.Axle1.DiscAndPad.rMuKinetic.Value = 0.5;
Vehicle.Brakes.Axle1.DiscAndPad.nTransition = struct;
Vehicle.Brakes.Axle1.DiscAndPad.nTransition.Units = 'rad/s';
Vehicle.Brakes.Axle1.DiscAndPad.nTransition.Comments = '';
Vehicle.Brakes.Axle1.DiscAndPad.nTransition.Value = 0.1;
Vehicle.Brakes.Axle1.DiscAndPad.dViscous = struct;
Vehicle.Brakes.Axle1.DiscAndPad.dViscous.Units = 'N*m/(rad/s)';
Vehicle.Brakes.Axle1.DiscAndPad.dViscous.Comments = '';
Vehicle.Brakes.Axle1.DiscAndPad.dViscous.Value = 0.001;
Vehicle.Brakes.Axle1.DiscAndPad.NPads = struct;
Vehicle.Brakes.Axle1.DiscAndPad.NPads.Units = '';
Vehicle.Brakes.Axle1.DiscAndPad.NPads.Comments = '';
Vehicle.Brakes.Axle1.DiscAndPad.NPads.Value = 4;
Vehicle.Brakes.Axle1.Caliper = struct;
Vehicle.Brakes.Axle1.Caliper.lCylinderDiameter = struct;
Vehicle.Brakes.Axle1.Caliper.lCylinderDiameter.Units = 'm';
Vehicle.Brakes.Axle1.Caliper.lCylinderDiameter.Comments = '';
Vehicle.Brakes.Axle1.Caliper.lCylinderDiameter.Value = 0.0125;
Vehicle.Brakes.Axle1.Caliper.pMax = struct;
Vehicle.Brakes.Axle1.Caliper.pMax.Units = '';
Vehicle.Brakes.Axle1.Caliper.pMax.Comments = '';
Vehicle.Brakes.Axle1.Caliper.pMax.Value = 85;
Vehicle.Brakes.Axle1.Caliper.fActuatorCutoff = struct;
Vehicle.Brakes.Axle1.Caliper.fActuatorCutoff.Units = '1/sec';
Vehicle.Brakes.Axle1.Caliper.fActuatorCutoff.Comments = '';
Vehicle.Brakes.Axle1.Caliper.fActuatorCutoff.Value = 40;
Vehicle.Brakes.Axle2 = struct;
Vehicle.Brakes.Axle2.DiscAndPad = struct;
Vehicle.Brakes.Axle2.DiscAndPad.lMeanRadius = struct;
Vehicle.Brakes.Axle2.DiscAndPad.lMeanRadius.Units = 'm';
Vehicle.Brakes.Axle2.DiscAndPad.lMeanRadius.Comments = '';
Vehicle.Brakes.Axle2.DiscAndPad.lMeanRadius.Value = 0.1;
Vehicle.Brakes.Axle2.DiscAndPad.rMuStatic = struct;
Vehicle.Brakes.Axle2.DiscAndPad.rMuStatic.Units = '';
Vehicle.Brakes.Axle2.DiscAndPad.rMuStatic.Comments = '(0-1)';
Vehicle.Brakes.Axle2.DiscAndPad.rMuStatic.Value = 0.7;
Vehicle.Brakes.Axle2.DiscAndPad.rMuKinetic = struct;
Vehicle.Brakes.Axle2.DiscAndPad.rMuKinetic.Units = '';
Vehicle.Brakes.Axle2.DiscAndPad.rMuKinetic.Comments = '(0-1)';
Vehicle.Brakes.Axle2.DiscAndPad.rMuKinetic.Value = 0.5;
Vehicle.Brakes.Axle2.DiscAndPad.nTransition = struct;
Vehicle.Brakes.Axle2.DiscAndPad.nTransition.Units = 'rad/s';
Vehicle.Brakes.Axle2.DiscAndPad.nTransition.Comments = '';
Vehicle.Brakes.Axle2.DiscAndPad.nTransition.Value = 0.1;
Vehicle.Brakes.Axle2.DiscAndPad.dViscous = struct;
Vehicle.Brakes.Axle2.DiscAndPad.dViscous.Units = 'N*m/(rad/s)';
Vehicle.Brakes.Axle2.DiscAndPad.dViscous.Comments = '';
Vehicle.Brakes.Axle2.DiscAndPad.dViscous.Value = 0.001;
Vehicle.Brakes.Axle2.DiscAndPad.NPads = struct;
Vehicle.Brakes.Axle2.DiscAndPad.NPads.Units = '';
Vehicle.Brakes.Axle2.DiscAndPad.NPads.Comments = '';
Vehicle.Brakes.Axle2.DiscAndPad.NPads.Value = 2;
Vehicle.Brakes.Axle2.Caliper = struct;
Vehicle.Brakes.Axle2.Caliper.lCylinderDiameter = struct;
Vehicle.Brakes.Axle2.Caliper.lCylinderDiameter.Units = 'm';
Vehicle.Brakes.Axle2.Caliper.lCylinderDiameter.Comments = '';
Vehicle.Brakes.Axle2.Caliper.lCylinderDiameter.Value = 0.0125;
Vehicle.Brakes.Axle2.Caliper.pMax = struct;
Vehicle.Brakes.Axle2.Caliper.pMax.Units = '';
Vehicle.Brakes.Axle2.Caliper.pMax.Comments = '';
Vehicle.Brakes.Axle2.Caliper.pMax.Value = 57;
Vehicle.Brakes.Axle2.Caliper.fActuatorCutoff = struct;
Vehicle.Brakes.Axle2.Caliper.fActuatorCutoff.Units = '1/sec';
Vehicle.Brakes.Axle2.Caliper.fActuatorCutoff.Comments = '';
Vehicle.Brakes.Axle2.Caliper.fActuatorCutoff.Value = 40;
Vehicle.Brakes.Type = 'Brakes';
Vehicle.Brakes.Instance = 'Axle2_PedalAbstract_DiscDisc_FSAE_Achilles';


% Set derived files from within Vehicle data structure

Vehicle = addfieldVehicleDW(Vehicle);

clear pinionIncl;
