function [Vehicle, VehicleData] = sm_car_read_database(workbookFile, exclsheetName, startRow, endRow)
%IMPORTFILE Import data from a spreadsheet
%  [Vehicle, VehicleData] = SM_CAR_IMPORT_VEHICLE_DATA_SHEET(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a cell array.
%
%  [Vehicle, VehicleData] = SM_CAR_IMPORT_VEHICLE_DATA_SHEET(FILE, SHEET) reads from the specified
%  worksheet.
%
%  [Vehicle, VehicleData] = SM_CAR_IMPORT_VEHICLE_DATA_SHEET(FILE, SHEET, STARTROW, ENDROW) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  STARTROW and ENDROW as a pair of scalars or vectors of matching size
%  for dis-contiguous row intervals.
%
%  Example:
%  VehicleData = sm_car_import_vehicle_data_sheet("Vehicle_Data.xlsx", "Sheet1", 2, 62);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Nov-2018 11:57:26

%% Input handling

% If no excluded sheet is specified, read all sheets
sheets = sheetnames(workbookFile);
if nargin == 1 || ~isempty(exclsheetName)
    sheets = erase(sheets,exclsheetName);
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 250;  % Ensure longer than entire table
end
%% Setup the Import Options
max_width = 26;
opts = spreadsheetImportOptions("NumVariables", max_width);

% Specify sheet and range
opts.Sheet = sheets;
opts.DataRange = "A" + startRow(1) + ":" + "Z" + endRow(1);

% Specify column names and types
%opts.VariableNames = ["Subsystem", "Part", "Quantity", "Units", "Comments", "x", "y", "z", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28"];
opts.VariableNames = "VarName"+string(1:max_width);
%opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts.VariableTypes = repmat("string",1,max_width);
%opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "WhitespaceRule", "preserve");
%opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], "EmptyFieldRule", "auto");
opts = setvaropts(opts, 1:max_width, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1:max_width, "EmptyFieldRule", "auto");

% Import the data
VehicleData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 1:length(startRow)
    opts.DataRange = "A" + startRow(idx) + ":" + "Z" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    VehicleData = [VehicleData; tb]; %#ok<AGROW>
end

%% Convert to output type
VehicleData = table2cell(VehicleData);
numIdx = cellfun(@(x) ~isnan(str2double(x)), VehicleData);
VehicleData(numIdx) = cellfun(@(x) {str2double(x)}, VehicleData(numIdx));


%% Most likely only keep this but keep everything for now

% Find vehicle data files

vehicle_data_file_list = dir('**/sm_car_ARTTU_*.xlsx');

% Go through files to get file names and category and initialize Vehicle
% struct
for i=1: size(vehicle_data_file_list,1)
data_file_name(i)=sort({vehicle_data_file_list(i).name});
data_file_categ(i)=erase(erase(data_file_name(i),'sm_car_ARTTU_'),'.xlsx');
Vehicle.(data_file_categ{i})=struct();
end

%% Read files


test=readtable("ARTTU_Brakes.xlsx",'Range','A5:E100');
test(all(ismissing(test), 2), :) = [];
for i=1:size(test,1)
if ~isempty(test.Var1{i})
temp=test.Var1{i};
else
test.Var1{i}=temp;
end
end