%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MATLAB Code Generated with Fuzzy Logic Designer App                     %
%                                                                         %
% Date: 08-May-2026 21:11:17                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function FIS_Builder(const)
% Construct FIS
T_S_FIS = sugfis(Name="T_S_FIS");
% Input 1
T_S_FIS = addInput(T_S_FIS,[0 21],Name="input1");
T_S_FIS = addMF(T_S_FIS,"input1","trapmf",[-0.1 0 5 12], ...
    Name="L",VariableType="input");
T_S_FIS = addMF(T_S_FIS,"input1","trimf",[5 12 19], ...
    Name="M",VariableType="input");
T_S_FIS = addMF(T_S_FIS,"input1","trapmf",[12 19 22 23], ...
    Name="H",VariableType="input");
% Input 2
T_S_FIS = addInput(T_S_FIS,[-0.5 0.5],Name="input2");
T_S_FIS = addMF(T_S_FIS,"input2","trapmf",[-0.6 -0.55 -0.3 -0.15], ...
    Name="NL",VariableType="input");
T_S_FIS = addMF(T_S_FIS,"input2","trimf",[-0.3 -0.15 -0], ...
    Name="NS",VariableType="input");
T_S_FIS = addMF(T_S_FIS,"input2","trimf",[-0.15 0 0.15], ...
    Name="ZR",VariableType="input");
T_S_FIS = addMF(T_S_FIS,"input2","trimf",[0 0.15 0.3], ...
    Name="PS",VariableType="input");
T_S_FIS = addMF(T_S_FIS,"input2","trapmf",[0.15 0.3 0.55 0.6], ...
    Name="PL",VariableType="input");
% Input 3
T_S_FIS = addInput(T_S_FIS,[-0.3 0.3],Name="input3");
T_S_FIS = addMF(T_S_FIS,"input3","zmf",[1.7 2315], ...
    Name="e_beta",VariableType="input");
% Input 4
T_S_FIS = addInput(T_S_FIS,[-1.5 1.5],Name="input4");
T_S_FIS = addMF(T_S_FIS,"input4","zmf",[1.7 2], ...
    Name="e_phi",VariableType="input");
% Output 1
T_S_FIS = addOutput(T_S_FIS,[-600 600],Name="output1");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(1,1) const(1,2) 0], ...
    Name="mf1",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(2,1) const(2,2) 0], ...
    Name="mf2",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(3,1) const(3,2) 0], ...
    Name="mf3",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(4,1) const(4,2) 0], ...
    Name="mf4",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(5,1) const(5,2) 0], ...
    Name="mf5",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(6,1) const(6,2) 0], ...
    Name="mf6",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(7,1) const(7,2) 0], ...
    Name="mf7",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(8,1) const(8,2) 0], ...
    Name="mf8",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(9,1) const(9,2) 0], ...
    Name="mf9",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(10,1) const(10,2) 0], ...
    Name="mf10",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(11,1) const(11,2) 0], ...
    Name="mf11",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(12,1) const(12,2) 0], ...
    Name="mf12",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(13,1) const(13,2) 0], ...
    Name="mf13",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(14,1) const(14,2) 0], ...
    Name="mf14",VariableType="output");
T_S_FIS = addMF(T_S_FIS,"output1","linear",[0 0 const(15,1) const(15,2) 0], ...
    Name="mf15",VariableType="output");
% Rules
T_S_FIS = addRule(T_S_FIS,[1 1 1 1 1 1 1; ...
    2 1 1 1 2 1 1; ...
    3 1 1 1 3 1 1; ...
    1 2 1 1 4 1 1; ...
    2 2 1 1 5 1 1; ...
    3 2 1 1 6 1 1; ...
    1 3 1 1 7 1 1; ...
    2 3 1 1 8 1 1; ...
    3 3 1 1 9 1 1; ...
    1 4 1 1 10 1 1; ...
    2 4 1 1 11 1 1; ...
    3 4 1 1 12 1 1; ...
    1 5 1 1 13 1 1; ...
    2 5 1 1 14 1 1; ...
    3 5 1 1 15 1 1]);
% Save FIS to specified MAT-file, overwriting any existing file
scriptDir = fileparts(mfilename('fullpath'));
outPath = fullfile(scriptDir, 'FIS_TS.mat');
% Save T_S_FIS variable to MAT-file, -v7.3 not required but safe for large objects
save(outPath, 'T_S_FIS', '-mat');
end
