clear; clc;
clear Vehicle_UKF_Step;

%%
% initial guess
x0 = [6e-5, 4e-6, 1e-4, 1e-3, 6e-5, 6e-5];

ukf_obj = UKF_Init(); 
ukf_obj.ProcessNoise = single(diag(x0));

%% 1. Load Data
DataSeries_Input = load("Skidpad_Input.mat");
DataSeries_Meas = load("Skidpad_Measurement.mat");
DataSeries_StateRef = load("Skidpad_StateRef.mat");

%% 2. Convert and Synchronize
% We use the Input's delta time as our "Master Clock"
% 'delta' is likely a timeseries, so we convert it to a timetable
tt_delta = timeseries2timetable(DataSeries_Input.data{1}.Values);
t_master = tt_delta.Time;

% --- Process INPUTS ---
% We synchronize all inputs to the master time grid
Input_Table = synchronize( ...
    timeseries2timetable(DataSeries_Input.data{1}.Values), ...
    timeseries2timetable(DataSeries_Input.data{2}.Values), ...
    timeseries2timetable(DataSeries_Input.data{3}.Values), ...
    timeseries2timetable(DataSeries_Input.data{4}.Values), ...
    timeseries2timetable(DataSeries_Input.data{5}.Values), ...
    t_master);

% --- Process MEASUREMENTS ---
% Bundle everything into one call. This guarantees they all have the same length.
Meas_Table = synchronize(...
    timeseries2timetable(DataSeries_Meas.data{1}.Values), ...
    timeseries2timetable(DataSeries_Meas.data{2}.Values), ...
    timeseries2timetable(DataSeries_Meas.data{3}.Values), ...
    timeseries2timetable(DataSeries_Meas.data{4}.Values), ...
    timeseries2timetable(DataSeries_Meas.data{5}.Values), ...
    timeseries2timetable(DataSeries_Meas.data{6}.Values), ...
    t_master); % Force align to t_master using Zero-Order Hold

% --- Process STATE REF ---
% Since StateRef is in a cell array, we convert each index
State_Table = synchronize(...
    timeseries2timetable(DataSeries_StateRef.data{1}.Values), ...
    timeseries2timetable(DataSeries_StateRef.data{2}.Values), ...
    timeseries2timetable(DataSeries_StateRef.data{3}.Values), ...
    timeseries2timetable(DataSeries_StateRef.data{4}.Values), ...
    timeseries2timetable(DataSeries_StateRef.data{5}.Values), ...
    timeseries2timetable(DataSeries_StateRef.data{6}.Values), ...
    t_master);

%% 3. Extract to Matrices
% .Variables automatically extracts the data columns into a matrix
Input    = Input_Table.Variables';   % [5 x N]
yMeas    = Meas_Table.Variables';    % [6 x N]
RefState = [State_Table.("VehBus.Chassis.Body.CG.vx")'; ...
            State_Table.("VehBus.Chassis.Body.CG.vy")'; ...
            State_Table.("VehBus.Chassis.Body.CG.aYaw")'; ...
            State_Table.("VehBus.Chassis.Body.CG.nYaw")'; ...
            State_Table.("VehBus.Chassis.Body.CG.gx")'; ...
            State_Table.("VehBus.Chassis.Body.CG.gy")'];   % [6 x N]
RefState(2,:) = atan2(RefState(2,:),RefState(1,:));
RefState(3,:) = unwrap(RefState(3,:));
for k = 1:size(Input,2)
State(:,k) = UKF(ukf_obj,single(yMeas(:,k)), single(Input(:,k)));
end
figure
for i = 1:6
    subplot(3,2,i)
    plot(t_master, State(i,:),t_master, RefState(i,:),'--y')
    xlabel('Time (s)')
    ylabel(sprintf('State(%d)', i))
    grid on
end
figure; plot(t_master, RefState(2,:), t_master, State(2,:))

