% -------------------------------------------------------------------
%  Generated by MATLAB on 7-Feb-2025 23:51:17
%  MATLAB version: 24.1.0.2653294 (R2024a) Update 5
% -------------------------------------------------------------------
                                               
sm_car_gen_init_database;
Init=IDatabase.Double_Lane_Change.FSAE_Achilles;